name: cifar-calib
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.2,<2.6
  - torchvision>=0.17,<0.21
  - matplotlib>=3.7
  - numpy>=1.24
  - tqdm>=4.66
  - pip
  - pip:
      - typing-extensions>=4.9
