name: euclid-calib
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.2
  - torchvision>=0.17
  - pytorch-cuda=12.1  # if you have NVIDIA GPU + recent driver; otherwise comment this line
  - numpy
  - matplotlib
  - tqdm
  - pip
  - pip:
      -
